---
name: Auto merge
on:
  pull_request:
jobs:
  auto-merge:
    uses: clouddrove/github-shared-workflows/.github/workflows/auto_merge.yml@1.0.9
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
    with:
      tfcheck: 'cloudwatch-billing-alert-to-pre-existing-sns-with-acct-id-example / Check code format'
...
